### ISSUE TITLE
fix biased getRandomQuote

### ISSUE THREAD

**Issue by hemirt** [gempir/gempbotgo#1]
NaM

**Comment by ThisWatcher** [comment]
pajaDank

**Comment by ThisWatcher** [comment]
does this ping hemirt? NaM

**Comment by gempir** [comment]
randomquotes are not exactly biased. The method of randomizing is just not very good, but I'll look into fixing it. So every quote has the same chance of getting picked.

**Comment by gempir** [comment]
Fixed in 1935ddb187256eef94aaee558522f57eb16c698b

Now all files of a user get loaded, which isn't super efficient, which is I will probably build a small cache in future.
